version: '3.2'

services:
  db:
    container_name: "kubernetes-homework-2-db"
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
  api:
    container_name: 'kubernetes-homework-2-api'
    build:
      context: .
      dockerfile: ./Dockerfile
    image: api-image
    ports:
      - 9000:9000
    depends_on:
      - db
    environment:
      - POSTGRES_CONNECTION_STRING="dbname=db user=postgres password=password host=host.docker.internal"
