apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  DB: ZGI=
  USER: cG9zdGdyZXM=
  PASSWORD: cGFzc3dvcmQ=
  CONNECTION_STRING: ZGJuYW1lPWRiIHVzZXI9cG9zdGdyZXMgcGFzc3dvcmQ9cGFzc3dvcmQgaG9zdD1ob3N0LmRvY2tlci5pbnRlcm5hbA==
